apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: default
spec:
  interval: 5m0s
  ref:
    branch: main
  url: https://github.com/pavlmark/mycluster-config
   ignore: |
    # exclude node service
     /*
    # include one file
     !/mycluster-config/kubernetes/fluxcd/repositories/example-app-1/deploy/node-service.yaml 
