apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-nfs-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sc-app-1
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /nfs-k8s
    server: 192.168.13.100
