#------------------------------------
# CI for GitOps, test environment    
#------------------------------------
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show files
        run: |
          cd mycluster-config/
          mkdir teeeest
          git add .
          git commit -m "Added test-dir"
          git push origin
