# ------------------------------------------
# GitGub Actions CI for FluxCD in kubernetes Cluster
# ------------------------------------------
name: CI-to-FluxCD-Kubernetes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci_work:
    name: update Docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd /home/pavl/mycluster-config/kubernetes/fluxcd/repositories/example-app-1/src
        docker build . -t pavlmark/example-app-1:0.0.5
        docker push pavlmark/example-app-1:0.0.5
  ci_for_kubernetes:
    runs-on: ubuntu-latest
    needs: ci_work
    steps:
    - uses: actions/checkout@v4
    - name: Change image
      run: |
        sed -i 's/image: pavlmark/example-app-1:0.0.4/image: pavlmark/example-app-1:0.0.5/g' ~/mycluster-config/kubernetest/fluxcd/repositories/deploy/deployment.yaml
